/*
Created: 07/05/2017
Modified: 07/05/2017
Model: EmpleadoPersistencia
Database: Oracle 11g Release 2
*/

-- Create sequences section -------------------------------------------------

CREATE SEQUENCE UNA.PLA_EMPLEADOS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 1
 NOCACHE;

CREATE SEQUENCE UNA.PLA_HISSALARIOS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 0
 NOCACHE;

-- Create tables section -------------------------------------------------

-- Table UNA.PLA_EMPLEADOS

CREATE TABLE UNA.PLA_EMPLEADOS(
    ID NUMBER NOT NULL,
    EMP_NOMBRE VARCHAR2(40 ) NOT NULL,
    EMP_APELLIDOS VARCHAR2(40 ) NOT NULL,
    EMP_FECHAING DATE NOT NULL,
    EMP_ESTADO VARCHAR2(1 ) NOT NULL CONSTRAINT PLA_EMPLEADOS_CK01 CHECK (EMP_ESTADO IN ('A', 'I')),
    EMP_VERSION NUMBER DEFAULT 1 NOT NULL
);

-- Add keys for table UNA.PLA_EMPLEADOS

ALTER TABLE UNA.PLA_EMPLEADOS ADD CONSTRAINT PLA_EMPLEADOS_PK PRIMARY KEY (ID);

-- Table and Columns comments section

COMMENT ON TABLE UNA.PLA_EMPLEADOS IS 'Tabla de empleados.';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.ID IS 'Id del empleado.';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.EMP_NOMBRE IS 'Nombre del empleado.';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.EMP_APELLIDOS IS 'Apellidos del empleado.';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.EMP_FECHAING IS 'Fecha de ingreso del empleado a la compañía.';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.EMP_ESTADO IS 'Estado del empleado (A:Activo, I:Inactivo).';
COMMENT ON COLUMN UNA.PLA_EMPLEADOS.EMP_VERSION IS 'Versión del registro.';

-- Table UNA.PLA_HISSALARIOS

CREATE TABLE UNA.PLA_HISSALARIOS(
    ID NUMBER NOT NULL,
    SAL_EMPID NUMBER NOT NULL,
    SAL_ANO NUMBER(4, 0) NOT NULL,
    SAL_MES NUMBER(2, 0) NOT NULL,
    SAL_MONTO NUMBER(14, 2) NOT NULL,
    SAL_VERSION NUMBER DEFAULT 1 NOT NULL
);

-- Add keys for table UNA.PLA_HISSALARIOS

ALTER TABLE UNA.PLA_HISSALARIOS ADD CONSTRAINT PLA_HISSALARIOS_PK PRIMARY KEY (ID);

-- Table and Columns comments section

COMMENT ON TABLE UNA.PLA_HISSALARIOS IS 'Tabla de históricos de salarios de los empleados.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.ID IS 'Id del histórico de salarios.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.SAL_EMPID IS 'Id del empleado.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.SAL_ANO IS 'Año del salario.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.SAL_MES IS 'Mes del salarios.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.SAL_MONTO IS 'Monto del salarios.';
COMMENT ON COLUMN UNA.PLA_HISSALARIOS.SAL_VERSION IS 'Versión del registro.';

-- Create relationships section -------------------------------------------------

ALTER TABLE UNA.PLA_HISSALARIOS ADD CONSTRAINT PLA_HISSALARIOS_FK01 FOREIGN KEY (SAL_EMPID) REFERENCES UNA.PLA_EMPLEADOS (ID);

-- Grant permissions section -------------------------------------------------