-- sum of salaries of employees 
-- with the letter 'AR' in their name
SELECT SUM(S.SAL_MONTO) AS TOTAL
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE UPPER(E.EMP_NOMBRE) LIKE '%AR%';

-- year, month, sum of salaries of employees
-- with the letter 'AR' in their name and active
SELECT S.SAL_ANO AS YEAR, S.SAL_MES AS MONTH, SUM(S.SAL_MONTO) AS TOTAL
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE UPPER(E.EMP_NOMBRE) LIKE '%AR%' AND E.EMP_ESTADO = 'A'
GROUP BY S.SAL_ANO, S.SAL_MES;

-- active employees with salaries more than 300000
SELECT DISTINCT E.*
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE S.SAL_MONTO > 300000 AND E.EMP_ESTADO = 'A';

-- year, salaries average of active employees where average > 300000
SELECT S.SAL_ANO AS YEAR, AVG(S.SAL_MONTO) AS AVERAGE
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE E.EMP_ESTADO = 'A'
GROUP BY SAL_ANO
HAVING AVG(S.SAL_MONTO) > 800000;

-- employee information salary, of employee with max salary in 2017
SELECT E.*, S.SAL_MONTO  
FROM PLA_EMPLEADOS E
JOIN  PLA_HISSALARIOS S ON E.ID = S.SAL_EMPID
WHERE SAL_ANO = '2015' AND S.SAL_MONTO = (
    SELECT MAX(S.SAL_MONTO) AS MAX_SALARY
    FROM PLA_HISSALARIOS S
    WHERE SAL_ANO = '2015'
);

-- same
WITH MAXIMUM AS (
    SELECT MAX(S.SAL_MONTO) MAX_SALARY 
    FROM PLA_HISSALARIOS S 
    WHERE S.SAL_ANO = '2015'
)   
SELECT E.*, S.SAL_MONTO 
FROM PLA_HISSALARIOS S 
JOIN MAXIMUM M ON M.MAX_SALARY = S.SAL_MONTO
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE S.SAL_ANO = '2015';

-- same
SELECT DISTINCT E.*, S.SAL_MONTO
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE S.SAL_ANO = '2015' AND S.SAL_MONTO = (
    SELECT MAX(S2.SAL_MONTO) 
    FROM PLA_HISSALARIOS S2 
    WHERE S2.SAL_ANO = '2015'
);

-- same
SELECT DISTINCT E.*, S.SAL_MONTO
FROM PLA_HISSALARIOS S
JOIN PLA_EMPLEADOS E ON E.ID = S.SAL_EMPID
WHERE S.SAL_ANO = '2015' AND S.SAL_MONTO = (
    SELECT MAX(S2.SAL_MONTO) 
    FROM PLA_HISSALARIOS S2 
    WHERE S2.SAL_ANO = S.SAL_ANO
);